### ISSUE TITLE
Train on customized dataset: how to get edge map?

### ISSUE THREAD

**Issue by lewisluk** [Catherine-R-He/HetNet#1]
My initial attemp will be using opencv 

`gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)`

I wonder if you have better way getting the edge map?

**Comment by Catherine-R-He** [comment]
Hi, thanks for your questions. In our experiments, we use Matlab codes for edge extraction. Below are the relevant codes. Hope it could help. 

```gt = imread(fullfile(data_root, [id '.png']));
gt = (gt > 0);
gt = double(gt);
[gy, gx] = gradient(gt);
temp_edge = gy.*gy + gx.*gx;
temp_edge(temp_edge~=0)=1;
bound = uint8(temp_edge*255);

**Comment by lewisluk** [comment]
Thank you very much
